name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd frontend
          yarn install --frozen-lockfile

      - name: Build project
        run: |
          cd frontend
          yarn build

  backend-lumen:
    name: Backend (Lumen) CI
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: lumen_db
        ports:
          - "3306:3306"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer

      - name: Install dependencies
        run: |
          cd backend-lumen
          composer install --no-dev --optimize-autoloader

      - name: Install PHPUnit (if missing)
        run: |
          cd backend-lumen
          composer require --dev phpunit/phpunit --prefer-dist

      - name: Set up environment variables
        run: |
          cp backend-lumen/.env.example backend-lumen/.env
          echo "DB_CONNECTION=mysql" >> backend-lumen/.env
          echo "DB_HOST=127.0.0.1" >> backend-lumen/.env
          echo "DB_PORT=3306" >> backend-lumen/.env
          echo "DB_DATABASE=lumen_db" >> backend-lumen/.env
          echo "DB_USERNAME=root" >> backend-lumen/.env
          echo "DB_PASSWORD=root" >> backend-lumen/.env
          echo "CACHE_DRIVER=file" >> backend-lumen/.env
          echo "APP_ENV=testing" >> backend-lumen/.env
          echo "APP_DEBUG=true" >> backend-lumen/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> backend-lumen/.env

      - name: Run migrations
        run: |
          cd backend-lumen
          php artisan migrate --force

      - name: Run tests
        run: |
          cd backend-lumen
          php vendor/bin/phpunit --testdox

  backend-node:
    name: Backend (Node.js) CI
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: node_db
        ports:
          - "3306:3306"

      redis:
        image: redis:latest
        ports:
          - "6379:6379"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd backend-node
          yarn install --frozen-lockfile

      - name: Set up environment variables
        run: |
          cp backend-node/.env.example backend-node/.env
          echo "DB_HOST=127.0.0.1" >> backend-node/.env
          echo "DB_PORT=3306" >> backend-node/.env
          echo "DB_DATABASE=node_db" >> backend-node/.env
          echo "DB_USERNAME=root" >> backend-node/.env
          echo "DB_PASSWORD=root" >> backend-node/.env
          echo "REDIS_HOST=127.0.0.1" >> backend-node/.env
          echo "REDIS_PORT=6379" >> backend-node/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> backend-node/.env

      - name: Run tests
        run: |
          cd backend-node
          npm run test
